// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgBans.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MtgBans.Data.Migrations
{
    [DbContext(typeof(MtgBansContext))]
    [Migration("20241031182156_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MtgBans.Data.Entities.Card", b =>
                {
                    b.Property<Guid>("ScryfallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("scryfall_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("ScryfallImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scryfall_image_url");

                    b.HasKey("ScryfallId")
                        .HasName("pk_cards");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("MtgBans.Data.Entities.CardLegalityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CardScryfallId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_scryfall_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_card_legality_event");

                    b.HasIndex("CardScryfallId")
                        .HasDatabaseName("ix_card_legality_event_card_scryfall_id");

                    b.ToTable("card_legality_event", (string)null);
                });

            modelBuilder.Entity("MtgBans.Data.Entities.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_formats");

                    b.ToTable("formats", (string)null);
                });

            modelBuilder.Entity("MtgBans.Data.Entities.FormatEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int?>("FormatId")
                        .HasColumnType("integer")
                        .HasColumnName("format_id");

                    b.HasKey("Id")
                        .HasName("pk_format_event");

                    b.HasIndex("FormatId")
                        .HasDatabaseName("ix_format_event_format_id");

                    b.ToTable("format_event", (string)null);
                });

            modelBuilder.Entity("MtgBans.Data.Entities.CardLegalityEvent", b =>
                {
                    b.HasOne("MtgBans.Data.Entities.Card", null)
                        .WithMany("LegalityEvents")
                        .HasForeignKey("CardScryfallId")
                        .HasConstraintName("fk_card_legality_event_cards_card_scryfall_id");
                });

            modelBuilder.Entity("MtgBans.Data.Entities.FormatEvent", b =>
                {
                    b.HasOne("MtgBans.Data.Entities.Format", null)
                        .WithMany("Events")
                        .HasForeignKey("FormatId")
                        .HasConstraintName("fk_format_event_formats_format_id");
                });

            modelBuilder.Entity("MtgBans.Data.Entities.Card", b =>
                {
                    b.Navigation("LegalityEvents");
                });

            modelBuilder.Entity("MtgBans.Data.Entities.Format", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
